Repository spacetelescope/gwcs, pull requests merged in 2018-09, with the labels that each got.

#174 Copy
  CHANGES.rst
  docs/gwcs/using_wcs.rst
  gwcs/tests/test_wcs.py
  gwcs/wcs.py
Labels: enhancement

#176 enable a flake8 test in Travis
  .travis.yml
  gwcs/__init__.py
  gwcs/coordinate_frames.py
  gwcs/tests/setup_package.py
  gwcs/utils.py
  gwcs/wcstools.py
Labels: testing

#177 Make reference_position docs match API
  gwcs/coordinate_frames.py
Labels: documentation, no_change_log_entry_needed
