Repository spacetelescope/gwcs, pull requests merged in 2018-05, with the labels that each got.

#153 fix test
  gwcs/tests/test_coordinate_systems.py
Labels: no_change_log_entry_needed, testing

#133 Coordinate to quantity
  CHANGES.rst
  gwcs/coordinate_frames.py
  gwcs/tests/test_coordinate_systems.py
  gwcs/tests/test_wcs.py
  gwcs/utils.py
  gwcs/wcs.py
Labels: enhancement

#155 remove more py2
  gwcs/tags/selectortags.py
  gwcs/tags/tests/test_selector.py
  gwcs/tags/wcs.py
Labels: no_change_log_entry_needed

#156 use ``with-units``
  CHANGES.rst
  docs/gwcs/using_wcs.rst
  gwcs/coordinate_frames.py
  gwcs/selector.py
  gwcs/tests/test_coordinate_systems.py
  gwcs/tests/test_region.py
  gwcs/tests/test_utils.py
  gwcs/tests/test_wcs.py
  gwcs/utils.py
  gwcs/wcs.py
Labels: enhancement, testing

#157 PEP 8 changes
  gwcs/coordinate_frames.py
  gwcs/tags/selectortags.py
  gwcs/tags/tests/test_selector.py
  gwcs/tags/wcs.py
  gwcs/tests/test_coordinate_systems.py
  gwcs/tests/test_region.py
  gwcs/tests/test_utils.py
  gwcs/tests/test_wcs.py
  gwcs/utils.py
  gwcs/wcs.py
Labels: no_change_log_entry_needed
