Repository spacetelescope/gwcs, pull requests merged in 2019-12, with the labels that each got.

#263 Improve world(pixel)_n_dim computation
  .travis.yml
  gwcs/api.py
  gwcs/tests/conftest.py
  gwcs/tests/test_api.py
Labels: APE 14

#256 Add direction cosines models
  CHANGES.rst
  gwcs/extension.py
  gwcs/schemas/stsci.edu/gwcs/direction_cosines-1.0.0.yaml
  gwcs/spectroscopy.py
  gwcs/tags/spectroscopy_models.py
  gwcs/tags/tests/test_spectroscopy.py
Labels: enhancement

#259 add grating equation models
  .travis.yml
  CHANGES.rst
  gwcs/spectroscopy.py
  gwcs/tests/test_spectroscopy_models.py
  setup.py
Labels: enhancement

#261 Ensure compliance with return types in APE 14 API
  gwcs/api.py
  gwcs/coordinate_frames.py
  gwcs/tests/test_api.py
Labels: APE 14

#258 Add tests and fix bugs in stokes frame with ape14
  CHANGES.rst
  gwcs/coordinate_frames.py
  gwcs/tests/conftest.py
  gwcs/tests/test_api.py
  gwcs/tests/test_coordinate_systems.py
Labels: APE 14, Stokes

#268 Py38
  .travis.yml
Labels: testing

#270 Add Snell and Sellmeier transforms
  CHANGES.rst
  docs/index.rst
  gwcs/schemas/stsci.edu/gwcs/sellmeier_glass-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/sellmeier_zemax-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/snell3d-1.0.0.yaml
  gwcs/spectroscopy.py
  gwcs/tags/__init__.py
  gwcs/tags/spectroscopy_models.py
  gwcs/tags/tests/test_spectroscopy.py
  gwcs/tests/conftest.py
  gwcs/tests/test_spectroscopy_models.py
Labels: enhancement, spectroscopy

#217 Add tests for the APE 14 slicing interface in astropy
  gwcs/api.py
  gwcs/coordinate_frames.py
  gwcs/tests/conftest.py
  gwcs/tests/test_api.py
  gwcs/tests/test_api_slicing.py
Labels: testing

#272 add a geometry module
  gwcs/api.py
  gwcs/coordinate_frames.py
  gwcs/geometry.py
  gwcs/selector.py
  gwcs/spectroscopy.py
  gwcs/tags/geometry_models.py
  gwcs/tags/spectroscopy_models.py
  gwcs/tags/tests/test_transforms.py
  gwcs/tests/test_spectroscopy_models.py
  gwcs/utils.py
  gwcs/wcstools.py
Labels: no_change_log_entry_needed

#273 Add grating equation schema
  .bandit.yaml
  gwcs/extension.py
  gwcs/schemas/stsci.edu/gwcs/grating_equation-1.0.0.yaml
  gwcs/tags/__init__.py
  gwcs/tags/spectroscopy_models.py
  gwcs/tags/tests/test_transforms.py
  setup.py
Labels: asdf_serialization
