Repository spacetelescope/gwcs, pull requests merged in 2019-01, with the labels that each got.

#198 Include support for energy in spectral frame
  gwcs/coordinate_frames.py
  gwcs/tests/test_coordinate_systems.py
Labels: coordinate_frames, enhancement

#164 Add a schema and tag for the StokesFrame
  gwcs/schemas/stsci.edu/gwcs/stokes_frame-1.0.0.yaml
  gwcs/tags/tests/test_wcs.py
  gwcs/tags/wcs.py
Labels: asdf_serialization, coordinate_frames, enhancement

#202 Fix travis
  .travis.yml
Labels: testing
