Repository spacetelescope/gwcs, pull requests merged in 2019-06, with the labels that each got.

#221 Fix CRPIX translation on main docs page
  docs/index.rst
Labels: documentation

#225 Update utils.isnumerical(...) to recognize big-endian dtypes
  CHANGES.rst
  gwcs/tests/test_utils.py
  gwcs/utils.py
Labels: bug

#220 pixel_to_world should always use with_units
  gwcs/api.py
Labels: WCS API, bug

#223 Fix numpy.test.utils import deprecation warnings
  gwcs/conftest.py
  gwcs/tests/test_region.py
  gwcs/tests/test_utils.py
Labels: testing

#208 Support velocity physical type in wcs validation
  gwcs/coordinate_frames.py
  gwcs/tests/test_coordinate_systems.py
Labels: physical types

#211 Use sphinx-asdf plugin to generate schema documentation
  .gitignore
  .rtd-environment.yml
  .travis.yml
  MANIFEST.in
  docs/conf.py
  docs/gwcs/schemas/celestial_frame-1.0.0.rst
  docs/gwcs/schemas/composite_frame-1.0.0.rst
  docs/gwcs/schemas/frame-1.0.0.rst
  docs/gwcs/schemas/frame2d-1.0.0.rst
  docs/gwcs/schemas/index.rst
  docs/gwcs/schemas/label_mapper-1.0.0.rst
  docs/gwcs/schemas/regions_selector-1.0.0.rst
  docs/gwcs/schemas/spectral_frame-1.0.0.rst
  docs/gwcs/schemas/step-1.0.0.rst
  docs/gwcs/schemas/temporal_frame-1.0.0.rst
  docs/gwcs/schemas/wcs-1.0.0.rst
  docs/sphinxext/__init__.py
  docs/sphinxext/category.py
  gwcs/schemas/stsci.edu/gwcs/label_mapper-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/regions_selector-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/wcs-1.0.0.yaml
Labels: documentation
