Repository spacetelescope/gwcs, pull requests merged in 2020-07, with the labels that each got.

#312 add 'input_frame' as an optional parameter to wcs_from_fiducial
  CHANGES.rst
  gwcs/wcstools.py
Labels: bug

#315 Include 'geometry' into doc build
  docs/index.rst
  gwcs/geometry.py
Labels: documentation, no_change_log_entry_needed

#313 Fix deprecated "ndarray from ragged nested sequences"
  .travis.yml
  gwcs/wcs.py
  setup.cfg
  setup.py
Labels: testing
