Repository spacetelescope/gwcs, pull requests merged in 2020-03, with the labels that each got.

#283 Fix NaN assignment in coordinate_frames
  gwcs/coordinate_frames.py
Labels: bug

#286 Add the ability to generate a SIP approximation to a GWCS imaging WCS
  CHANGES.rst
  gwcs/tests/data/miriwcs.asdf
  gwcs/tests/test_wcs.py
  gwcs/wcs.py
Labels: enhancement

#288 add a UCD1 to CTYPE mapping
  CHANGES.rst
  gwcs/coordinate_frames.py
Labels: coordinate_frames

#289 make bounding-box optional
  gwcs/coordinate_frames.py
  gwcs/tests/test_wcs.py
  gwcs/wcs.py
Labels: no_change_log_entry_needed
