Repository spacetelescope/gwcs, pull requests merged in 2020-11, with the labels that each got.

#295 Add ability to convert WCS to FITS WCS -TAB
  CHANGES.rst
  gwcs/tests/conftest.py
  gwcs/tests/data/miri_lrs_wcs.asdf
  gwcs/tests/test_wcs.py
  gwcs/wcs.py
  setup.py
Labels: enhancement

#324 Iterative inverse for imaging WCS
  CHANGES.rst
  gwcs/tests/data/nircamwcs.asdf
  gwcs/tests/test_wcs.py
  gwcs/wcs.py
  setup.py
Labels: enhancement

#311 Fix a bug when using CoordinateFrame directly
  gwcs/coordinate_frames.py
  gwcs/tests/test_coordinate_systems.py
  gwcs/wcs.py
Labels: bug, coordinate_frames

#325 Fixes for Astropy wcsapi
  gwcs/coordinate_frames.py
  gwcs/tests/test_api.py
  gwcs/tests/test_coordinate_systems.py
  gwcs/tests/test_wcs.py
  gwcs/utils.py
Labels: APE 14, coordinate_frames

#328 Fix typos in numerical_inverse docstring
  gwcs/wcs.py
Labels: documentation, no_change_log_entry_needed
