Repository spacetelescope/gwcs, pull requests merged in 2021-12, with the labels that each got.

#382 Update region.py
  CHANGES.rst
  gwcs/region.py
  gwcs/tests/test_region.py
Labels: bug

#371 Convert to asdf Converters
  CHANGES.rst
Labels: asdf_serialization

#388 Convert to asdf Converters
  CHANGES.rst
  docs/gwcs/schemas/index.rst
  docs/gwcs/wcs_validation.rst
  docs/index.rst
  gwcs/converters/__init__.py
  gwcs/converters/geometry.py
  gwcs/converters/selector.py
  gwcs/converters/spectroscopy.py
  gwcs/converters/tests/__init__.py
  gwcs/converters/tests/test_selector.py
  gwcs/converters/tests/test_transforms.py
  gwcs/converters/tests/test_wcs.py
  gwcs/converters/wcs.py
  gwcs/extension.py
  gwcs/geometry.py
  gwcs/schemas/stsci.edu/gwcs/celestial_frame-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/composite_frame-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/direction_cosines-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/direction_cosines-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/frame-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/frame2d-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/grating_equation-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/grating_equation-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/label_mapper-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/label_mapper-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/regions_selector-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/regions_selector-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/sellmeier_glass-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/sellmeier_glass-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/sellmeier_zemax-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/sellmeier_zemax-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/snell3d-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/snell3d-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/spectral_frame-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/spherical_cartesian-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/spherical_cartesian-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/step-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/step-1.1.0.yaml
  gwcs/schemas/stsci.edu/gwcs/stokes_frame-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/temporal_frame-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/wcs-1.0.0.yaml
  gwcs/schemas/stsci.edu/gwcs/wcs-1.1.0.yaml
  gwcs/spectroscopy.py
  gwcs/tags/__init__.py
  gwcs/tags/spectroscopy_models.py
  gwcs/tags/tests/__init__.py
  gwcs/tags/tests/test_selector.py
  gwcs/tags/wcs.py
  gwcs/tests/test_geometry.py
  gwcs/wcs.py
  setup.cfg
  setup.py
Labels: asdf_serialization, keep-up-with-asdf

#375 Enable Compound Bounding Box support
  CHANGES.rst
  gwcs/tests/test_wcs.py
  gwcs/wcs.py
Labels: enhancement, bbox

#394 MNT: Do not use enable_deprecations_as_exceptions
  conftest.py
Labels: MNT
