Repository spacetelescope/gwcs, pull requests merged in 2024-12, with the labels that each got.

#526 Ignore the bounding box ordering warning when reading files
  CHANGES.rst
  gwcs/converters/wcs.py
  gwcs/examples.py
  gwcs/tests/test_wcs.py
Labels: Downstream CI

#525 Add integer rounding to match APE 14
  CHANGES.rst
  gwcs/api.py
Labels: no-changelog-entry-needed

#532 Set the bounding_box within the forward_transform property
  CHANGES.rst
  gwcs/wcs.py
Labels: Downstream CI

#498 Respect the bounding_box in inverse transforms
  CHANGES.rst
  gwcs/api.py
  gwcs/tests/conftest.py
  gwcs/tests/test_api.py
  gwcs/tests/test_api_slicing.py
  gwcs/tests/test_bounding_box.py
  gwcs/tests/test_coordinate_systems.py
  gwcs/tests/test_utils.py
  gwcs/tests/test_wcs.py
  gwcs/utils.py
  gwcs/wcs.py
Labels: Downstream CI

#536 Fix inside/outside calc for inverse with bbox
  CHANGES.rst
  gwcs/examples.py
  gwcs/tests/conftest.py
  gwcs/tests/test_api.py
  gwcs/wcs.py
Labels: bug

#537 Allow for small rounding errors in bbox for inverse
  gwcs/wcs.py
Labels: bug, enhancement, no-changelog-entry-needed

#538 Revert "Allow for small rounding errors in bbox for inverse"
  gwcs/wcs.py
Labels: no-changelog-entry-needed

#541 Update changes for release
  CHANGES.rst
Labels: no-changelog-entry-needed

#542 Update stable branch of 0.22.0
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/contexts.yml
  .github/workflows/downstream.yml
  .github/workflows/romanisim_data.yml
  CHANGES.rst
  README.rst
  docs/gwcs/points_to_wcs.rst
  docs/gwcs/using_wcs.rst
  docs/index.rst
  gwcs/api.py
  gwcs/converters/wcs.py
  gwcs/coordinate_frames.py
  gwcs/examples.py
  gwcs/region.py
  gwcs/tests/conftest.py
  gwcs/tests/data/miri_lrs_wcs.asdf
  gwcs/tests/data/miriwcs.asdf
  gwcs/tests/data/nircamwcs.asdf
  gwcs/tests/test_api.py
  gwcs/tests/test_api_slicing.py
  gwcs/tests/test_bounding_box.py
  gwcs/tests/test_coordinate_systems.py
  gwcs/tests/test_utils.py
  gwcs/tests/test_wcs.py
  gwcs/utils.py
  gwcs/wcs.py
  gwcs/wcstools.py
  pyproject.toml
  requirements-dev.txt
  tox.ini
Labels: no-changelog-entry-needed

#540 Fix inequality sign and var name in outside bbox test
  gwcs/wcs.py
Labels: bug, no_change_log_entry_needed, no-changelog-entry-needed
