Repository spacetelescope/gwcs, pull requests merged in 2024-09, with the labels that each got.

#508 Simplify converting units to strings
  gwcs/wcs.py
Labels: WCS API, MNT, no-changelog-entry-needed

#509 Update development version installation instructions
  README.rst
Labels: documentation, no-changelog-entry-needed

#510 Improve compatibility with numpy 2.0
  gwcs/region.py
Labels: MNT, no-changelog-entry-needed
