Repository spacetelescope/gwcs, pull requests merged in 2025-04, with the labels that each got.

#575 Pull all tags in rtd
  .readthedocs.yaml
Labels: documentation, no-changelog-entry-needed

#576 rename `webbpsf` -> `stpsf`
  .github/workflows/downstream.yml
  .github/workflows/romanisim_data.yml
Labels: no-changelog-entry-needed

#577 Standardize the version setting scheme and fix version displayed in the docs
  .gitignore
  .readthedocs.yaml
  docs/conf.py
  gwcs/__init__.py
  pyproject.toml
  tox.ini
Labels: no-changelog-entry-needed

#580 Switch to using furo theme
  CHANGES.rst
  docs/_static/images/stsci_logo.png
  docs/_templates/autosummary/base.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/conf.py
  docs/gwcs/api.rst
  docs/index.rst
  gwcs/coordinate_frames.py
  gwcs/selector.py
  pyproject.toml
Labels: documentation

#583 Replace deprecated isiterable
  gwcs/converters/selector.py
  gwcs/coordinate_frames.py
Labels: no-changelog-entry-needed

#585 [SCSB-205] `project.license.file` -> `project.license-files`
  pyproject.toml
Labels: no-changelog-entry-needed
